### ISSUE TITLE
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by babakmdi** [alexsee/simple-recorder#1]
hi sir, when i want start the application this message show, what should i do ?

![image](https://user-images.githubusercontent.com/65450661/122746855-ae401380-d29f-11eb-98f8-e7ae147f0045.png)

**Comment by babakmdi** [comment]
hello sir what should i do for this?

**Comment by alexsee** [comment]
The desktop recorder app comes with a companion Win32 app which must be able to run as a full trust app. So you have to set the application package as your startup project, otherwise you may receive this exception.
